# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'esd2_GUI.ui'
#
# Created: Sun Apr 30 20:57:53 2023
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_TabWidget(object):
    def setupUi(self, TabWidget):
        TabWidget.setObjectName(_fromUtf8("TabWidget"))
        TabWidget.resize(986, 709)
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_6 = QtGui.QLabel(self.tab)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 0, 0, 1, 1)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.widget_4 = QtGui.QWidget(self.tab)
        self.widget_4.setObjectName(_fromUtf8("widget_4"))
        self.horizontalLayout_12.addWidget(self.widget_4)
        self.pushButton_3 = QtGui.QPushButton(self.tab)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.horizontalLayout_12.addWidget(self.pushButton_3)
        self.gridLayout_2.addLayout(self.horizontalLayout_12, 1, 0, 1, 1)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.widget_3 = QtGui.QWidget(self.tab)
        self.widget_3.setMinimumSize(QtCore.QSize(670, 520))
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.horizontalLayout_9.addWidget(self.widget_3)
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_4 = QtGui.QLabel(self.tab)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_10.addWidget(self.label_4)
        self.progressBar_3 = QtGui.QProgressBar(self.tab)
        self.progressBar_3.setProperty("value", 24)
        self.progressBar_3.setObjectName(_fromUtf8("progressBar_3"))
        self.horizontalLayout_10.addWidget(self.progressBar_3)
        self.verticalLayout_12.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_5 = QtGui.QLabel(self.tab)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_11.addWidget(self.label_5)
        self.progressBar_4 = QtGui.QProgressBar(self.tab)
        self.progressBar_4.setProperty("value", 24)
        self.progressBar_4.setObjectName(_fromUtf8("progressBar_4"))
        self.horizontalLayout_11.addWidget(self.progressBar_4)
        self.verticalLayout_12.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_9.addLayout(self.verticalLayout_12)
        self.gridLayout_2.addLayout(self.horizontalLayout_9, 2, 0, 1, 1)
        TabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab1 = QtGui.QWidget()
        self.tab1.setObjectName(_fromUtf8("tab1"))
        self.gridLayout = QtGui.QGridLayout(self.tab1)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_3 = QtGui.QLabel(self.tab1)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.pushButton = QtGui.QPushButton(self.tab1)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout_5.addWidget(self.pushButton)
        self.lcdNumber = QtGui.QLCDNumber(self.tab1)
        self.lcdNumber.setObjectName(_fromUtf8("lcdNumber"))
        self.horizontalLayout_5.addWidget(self.lcdNumber)
        self.pushButton_2 = QtGui.QPushButton(self.tab1)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout_5.addWidget(self.pushButton_2)
        self.widget_2 = QtGui.QWidget(self.tab1)
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.horizontalLayout_5.addWidget(self.widget_2)
        self.gridLayout.addLayout(self.horizontalLayout_5, 1, 0, 1, 1)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.widget = QtGui.QWidget(self.tab1)
        self.widget.setMinimumSize(QtCore.QSize(670, 520))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout_8.addWidget(self.widget)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.tableWidget = QtGui.QTableWidget(self.tab1)
        self.tableWidget.setMinimumSize(QtCore.QSize(271, 281))
        self.tableWidget.setMaximumSize(QtCore.QSize(271, 281))
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(8)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.verticalLayout_11.addWidget(self.tableWidget)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label = QtGui.QLabel(self.tab1)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_7.addWidget(self.label)
        self.progressBar = QtGui.QProgressBar(self.tab1)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.horizontalLayout_7.addWidget(self.progressBar)
        self.verticalLayout_11.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_2 = QtGui.QLabel(self.tab1)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_6.addWidget(self.label_2)
        self.progressBar_2 = QtGui.QProgressBar(self.tab1)
        self.progressBar_2.setProperty("value", 24)
        self.progressBar_2.setObjectName(_fromUtf8("progressBar_2"))
        self.horizontalLayout_6.addWidget(self.progressBar_2)
        self.verticalLayout_11.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_8.addLayout(self.verticalLayout_11)
        self.gridLayout.addLayout(self.horizontalLayout_8, 2, 0, 1, 1)
        TabWidget.addTab(self.tab1, _fromUtf8(""))

        self.retranslateUi(TabWidget)
        TabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.lcdNumber.update)
        QtCore.QObject.connect(self.pushButton_2, QtCore.SIGNAL(_fromUtf8("clicked()")), self.lcdNumber.update)
        QtCore.QMetaObject.connectSlotsByName(TabWidget)

    def retranslateUi(self, TabWidget):
        TabWidget.setWindowTitle(_translate("TabWidget", "TabWidget", None))
        self.label_6.setText(_translate("TabWidget", "Instructions: Take a total of 8 photos of the court with the ball in the same position. \n"
"After each photo move the camera around the court. \n"
"The scatter plot below will show the accuracy of the system.", None))
        self.pushButton_3.setText(_translate("TabWidget", "Reset", None))
        self.label_4.setText(_translate("TabWidget", "Current Accuracy", None))
        self.label_5.setText(_translate("TabWidget", "Loop Time          ", None))
        TabWidget.setTabText(TabWidget.indexOf(self.tab), _translate("TabWidget", "Static Camera", None))
        self.label_3.setText(_translate("TabWidget", "Instructions: Take a total of 8 photos of the court with the ball in the same position. \n"
"After each photo move the camera around the court. \n"
"The scatter plot below will show the accuracy of the system.", None))
        self.pushButton.setText(_translate("TabWidget", "Capture", None))
        self.pushButton_2.setText(_translate("TabWidget", "Reset", None))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("TabWidget", "Ball 1", None))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("TabWidget", "Ball 2", None))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("TabWidget", "Ball 3", None))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("TabWidget", "Ball 4", None))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("TabWidget", "Ball 5", None))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("TabWidget", "Ball 6", None))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("TabWidget", "Ball 7", None))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("TabWidget", "Ball 8", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("TabWidget", "X", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("TabWidget", "Y", None))
        self.label.setText(_translate("TabWidget", "Current Accuracy", None))
        self.label_2.setText(_translate("TabWidget", "Loop Time          ", None))
        TabWidget.setTabText(TabWidget.indexOf(self.tab1), _translate("TabWidget", "Static Ball", None))

